services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular19-app
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true